import { useState, useEffect, useCallback } from "react";

const NPC_DATA = [
  // Classic
  { name: "Edwin VanCleef", title: "Leader of the Defias Brotherhood", role: "Final Boss", hint: "A master assassin who built his criminal empire in Westfall after being betrayed by Stormwind nobles.", model: "Human Rogue — hooded, dual daggers, red bandana", dungeon: "The Deadmines", expansion: "Classic", wrongOptions: ["Shadowfang Keep", "The Stockade", "Wailing Caverns"] },
  { name: "Herod", title: "The Scarlet Champion", role: "Mini-Boss", hint: "A legendary warrior of the Scarlet Crusade, infamous for his whirlwind attack that wipes unprepared groups.", model: "Human Warrior — heavy scarlet plate armor, massive axe", dungeon: "Scarlet Monastery", expansion: "Classic", wrongOptions: ["Stratholme", "Scholomance", "Blackrock Depths"] },
  { name: "High Inquisitor Whitemane", title: "Leader of the Scarlet Crusade", role: "Final Boss", hint: "She can resurrect her fallen champion mid-fight, forcing you to burn them both down simultaneously.", model: "Human Priest — white robes, red hair, holy censer", dungeon: "Scarlet Monastery", expansion: "Classic", wrongOptions: ["Stratholme", "Uldaman", "Shadowfang Keep"] },
  { name: "Baron Rivendare", title: "Champion of the Scourge", role: "Final Boss", hint: "Notorious for an extremely rare mount drop that made him one of the most farmed bosses in classic WoW.", model: "Death Knight — skeletal horse mount, dark plate armor, glowing sword", dungeon: "Stratholme", expansion: "Classic", wrongOptions: ["Scholomance", "Shadowfang Keep", "Blackrock Depths"] },
  { name: "Darkmaster Gandling", title: "Headmaster of Scholomance", role: "Final Boss", hint: "He randomly teleports party members into locked side rooms full of undead students during the fight.", model: "Undead Mage — black robes, skull staff, tattered hat", dungeon: "Scholomance", expansion: "Classic", wrongOptions: ["Stratholme", "Uldaman", "Scarlet Monastery"] },
  { name: "Gahz'rilla", title: "The Hydra God", role: "Boss", hint: "You need Marvon's Warbell to summon this massive basilisk-hydra creature lurking in a pool of water.", model: "Giant hydra — blue-scaled, multi-headed, serpentine", dungeon: "Zul'Farrak", expansion: "Classic", wrongOptions: ["Temple of Atal'Hakkar", "Razorfen Downs", "Maraudon"] },
  { name: "Princess Theradras", title: "Daughter of Therazane", role: "Final Boss", hint: "A gigantic earth elemental princess, lover of the centaur demigod Zaetar, found at the end of a purple underground river.", model: "Earth Elemental — massive stone body, lumbering, female form", dungeon: "Maraudon", expansion: "Classic", wrongOptions: ["Blackfathom Deeps", "Razorfen Kraul", "Dire Maul"] },
  { name: "Emperor Dagran Thaurissan", title: "Emperor of the Dark Iron Dwarves", role: "Final Boss", hint: "He holds Princess Moira Bronzebeard captive — though she may not want to be rescued.", model: "Dark Iron Dwarf — regal emperor robes, fiery beard, crown", dungeon: "Blackrock Depths", expansion: "Classic", wrongOptions: ["Upper Blackrock Spire", "Molten Core", "Dire Maul"] },
  { name: "General Drakkisath", title: "Commander of the Black Dragonflight", role: "Final Boss", hint: "You need his blood to enter Blackwing Lair — he breathes fire in a cone that melts careless raid groups.", model: "Dragonspawn — tall, chromatic-scaled, imposing general", dungeon: "Upper Blackrock Spire", expansion: "Classic", wrongOptions: ["Blackrock Depths", "Lower Blackrock Spire", "Onyxia's Lair"] },
  { name: "Lord Godfrey", title: "Betrayer of Gilneas", role: "Final Boss", hint: "A Gilnean nobleman so disgusted by the Worgen curse that he defected — and died — rather than accept it.", model: "Undead Human — tattered nobleman coat, pistols, undead pallor", dungeon: "Shadowfang Keep", expansion: "Classic", wrongOptions: ["Scarlet Monastery", "Scholomance", "The Stockade"] },
  { name: "Mutanus the Devourer", title: "Servant of the Defiler", role: "Final Boss", hint: "A massive sea creature summoned by the Druids of the Fang at the end of a snake-infested canyon.", model: "Naga Sea Witch — serpentine, large, glowing eyes", dungeon: "Wailing Caverns", expansion: "Classic", wrongOptions: ["Blackfathom Deeps", "Razorfen Kraul", "The Deadmines"] },
  { name: "Aku'mai", title: "The Darkest Tide", role: "Final Boss", hint: "A massive hydra sleeping beneath an ancient Night Elf temple at the bottom of a submerged ruin.", model: "Hydra — blue-grey scales, many heads, enormous size", dungeon: "Blackfathom Deeps", expansion: "Classic", wrongOptions: ["Wailing Caverns", "Maraudon", "Temple of Atal'Hakkar"] },
  { name: "Archaedas", title: "Guardian of the Discs", role: "Final Boss", hint: "An ancient titan construct who activates surrounding earthen when he takes damage, controlling the Discs of Norgannon.", model: "Stone Titan — colossal, ancient, blue-glowing runes", dungeon: "Uldaman", expansion: "Classic", wrongOptions: ["Gnomeregan", "Blackrock Depths", "Dire Maul"] },
  { name: "Mekgineer Thermaplugg", title: "Usurper of Gnomeregan", role: "Final Boss", hint: "A mad gnomish engineer who irradiated his own city and exiled his own people to seize power.", model: "Gnome — enormous mechanical suit, crazed goggles, oversized machine", dungeon: "Gnomeregan", expansion: "Classic", wrongOptions: ["Uldaman", "Blackrock Depths", "The Deadmines"] },

  // Burning Crusade
  { name: "Murmur", title: "Entity of Sound", role: "Final Boss", hint: "An ancient being composed entirely of sonic energy — his Sonic Boom can one-shot anyone not hiding behind pillars.", model: "Void creature — pulsating purple-black mass, no discernible face", dungeon: "Shadow Labyrinth", expansion: "The Burning Crusade", wrongOptions: ["Mana-Tombs", "Sethekk Halls", "The Arcatraz"] },
  { name: "Warp Splinter", title: "Ancient of the Botanica", role: "Final Boss", hint: "A corrupted treant who summons miniature treant saplings to overwhelm the party.", model: "Giant Ancient — twisted bark, glowing blue eyes, enormous treant form", dungeon: "The Botanica", expansion: "The Burning Crusade", wrongOptions: ["The Mechanar", "The Arcatraz", "Shadow Labyrinth"] },
  { name: "Kargath Bladefist", title: "Warchief of the Fel Horde", role: "Final Boss", hint: "His right hand was replaced with a blade — he severed it himself to escape an ogre prison.", model: "Orc Warrior — massive, blade for a fist, spiked fel armor, snarling", dungeon: "The Shattered Halls", expansion: "The Burning Crusade", wrongOptions: ["Hellfire Ramparts", "The Blood Furnace", "Mana-Tombs"] },
  { name: "Nexus-Prince Shaffar", title: "Ethereal Prince", role: "Final Boss", hint: "An ethereal crime lord who sends beacons to summon adds — killing them before they activate is key.", model: "Ethereal — bandaged void being, floating, golden jewelry, staff", dungeon: "Mana-Tombs", expansion: "The Burning Crusade", wrongOptions: ["Shadow Labyrinth", "The Arcatraz", "Sethekk Halls"] },
  { name: "Talon King Ikiss", title: "Ruler of the Arakkoa", role: "Final Boss", hint: "He casts a deadly Arcane Explosion that players must hide behind pillars to survive.", model: "Arakkoa — bird-like, feathered, crown, staff, ancient robes", dungeon: "Sethekk Halls", expansion: "The Burning Crusade", wrongOptions: ["Mana-Tombs", "Shadow Labyrinth", "Auchenai Crypts"] },
  { name: "Pathaleon the Calculator", title: "Destructor of Worlds", role: "Final Boss", hint: "A blood elf construct-master controlling a robot army in a floating Netherstorm fortress.", model: "Blood Elf — pale, slim, arcane-infused robes, calculating gaze", dungeon: "The Mechanar", expansion: "The Burning Crusade", wrongOptions: ["The Botanica", "The Arcatraz", "Mana-Tombs"] },
  { name: "Epoch Hunter", title: "Servant of the Infinite Dragonflight", role: "Final Boss", hint: "He arrives to stop you from preventing the burning of Southshore in an alternate Hillsbrad timeline.", model: "Dragon — skeletal, sand-colored, ancient, distorted temporal form", dungeon: "Old Hillsbrad Foothills", expansion: "The Burning Crusade", wrongOptions: ["Black Morass", "Caverns of Time: Durnholde", "Shadow Labyrinth"] },
  { name: "Harbinger Skyriss", title: "Imprisoned Ethereal Warlord", role: "Final Boss", hint: "He creates a copy of himself at 25% health — only one is real, the other is a psychic illusion.", model: "Ethereal — crackling void energy, dark bandaging, imposing armored form", dungeon: "The Arcatraz", expansion: "The Burning Crusade", wrongOptions: ["Mana-Tombs", "Shadow Labyrinth", "The Botanica"] },

  // Wrath of the Lich King
  { name: "Ingvar the Plunderer", title: "Vrykul Warrior", role: "Final Boss", hint: "He dies and is raised by his Val'kyr mid-fight, forcing you to fight him twice — as a mortal and as undead.", model: "Vrykul — massive Viking warrior, horned helm, battle axe, then undead form", dungeon: "Utgarde Keep", expansion: "Wrath of the Lich King", wrongOptions: ["Utgarde Pinnacle", "Halls of Stone", "Gundrak"] },
  { name: "King Dred", title: "The Raptor King", role: "Boss", hint: "A colossal devilsaur — the largest non-raid creature you fight in a dungeon — with debuffs that stack quickly.", model: "Devilsaur — enormous tyrannosaurus-like dinosaur, tusked, armored", dungeon: "Drak'Tharon Keep", expansion: "Wrath of the Lich King", wrongOptions: ["Gundrak", "Zul'Drak", "Utgarde Keep"] },
  { name: "Keristrasza", title: "Enslaved Red Dragon", role: "Final Boss", hint: "She was captured and tortured by Malygos — she begs players to kill her to end her suffering.", model: "Red Dragon — chained, corrupted coloring, eyes filled with madness", dungeon: "The Nexus", expansion: "Wrath of the Lich King", wrongOptions: ["The Oculus", "Halls of Lightning", "Violet Hold"] },
  { name: "Anub'arak", title: "Traitor King", role: "Final Boss", hint: "An ancient nerubian king raised by the Lich King — he tunnels underground to summon scarab adds.", model: "Nerubian — massive spider-like undead creature, chitinous carapace", dungeon: "Azjol-Nerub", expansion: "Wrath of the Lich King", wrongOptions: ["Ahn'kahet", "Pit of Saron", "Utgarde Keep"] },
  { name: "Herald Volazj", title: "Voice of the Old Gods", role: "Final Boss", hint: "He traps each party member in an insanity realm where they must fight illusions of their own teammates.", model: "Faceless One — towering, multi-tentacled, Old God servant", dungeon: "Ahn'kahet: The Old Kingdom", expansion: "Wrath of the Lich King", wrongOptions: ["Azjol-Nerub", "Halls of Stone", "Violet Hold"] },
  { name: "Loken", title: "Prime Designate of the Titans", role: "Final Boss", hint: "His Lightning Nova forces the group to stack on top of him — counterintuitive but the only way to survive.", model: "Iron Vrykul — armored titan keeper, crackling with lightning, imposing", dungeon: "Halls of Lightning", expansion: "Wrath of the Lich King", wrongOptions: ["Halls of Stone", "Ulduar", "Utgarde Pinnacle"] },
  { name: "Mal'Ganis", title: "Nathrezim